name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@v1
      env:
          # 注意在 Settings->Secrets 配置 GITEE_SSH_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:Snailclimb/springboot-guide.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:SnailClimb/springboot-guide.git"
